// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhxvhbiqcwfaatwofidw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoeHZoYmlxY3dmYWF0d29maWR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTQyMjcsImV4cCI6MjA2OTI5MDIyN30.66k-H5nEToYFHq5MdZRd3b2sL0eFVRh1AIx2X_dJ_Ag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});